name:                flinch
version:             0.1.0.0
github:              "githubuser/rjdestigter"
license:             BSD3
author:              "John de Stigter"
maintainer:          "johndestigter@gmail.com"
copyright:           "2020 John de Stigter"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/flinch#readme>

dependencies:
- base >= 4.7 && < 5
- polysemy
# - polysemy-plugin >= 0.2.3.0 && < 0.3
# - polysemy-zoo >= 0.6.0.1 && < 0.7

default-extensions:
  # Recommended extensions for polysemy
  - DataKinds
  - FlexibleContexts
  - GADTs
  - LambdaCase
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - TypeApplications
  - TypeOperators
  - TypeFamilies
  - TemplateHaskell

library:
  source-dirs: src

executables:
  flinch-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flinch

tests:
  flinch-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flinch
